# Generated by Django 3.0.10 on 2022-08-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_remove_actors_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='salary',
            field=models.FloatField(default=10000),
        ),
    ]
