# Generated by Django 3.0.10 on 2022-08-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_auto_20220804_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
